# -*- coding: utf-8 -*-
"""Implementing and Evaluating Logistic Regression from Scratch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wREt6x3TqGKuMDp4c5WYQwp3WciVuMzV
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

#------------------------------
#1. Generate binary dataset
#------------------------------
X, y = make_classification(n_samples=500, n_features=2, n_informative=2, n_redundant=0, n_classes=2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#------------------------------
#2 & 3. Logistic Regression from Scratch
#------------------------------
class LogisticRegressionScratch:
  def __init__(self, lr=0.1, epochs=1000):
    self.lr = lr
    self.epochs = epochs

  def sigmoid(self, z):
    return 1 / (1 + np.exp(-z))

  def fit(self, X, y):
    n_samples, n_features = X.shape
    self.weights = np.zeros(n_features)
    self.bias = 0
    self.costs = []

    for _ in range(self.epochs):
      linear_model = np.dot(X, self.weights) + self.bias
      y_pred = self.sigmoid(linear_model)

      # Binary Cross-Entropy Cost
      cost = -(1/n_samples) * np.sum(y * np.log(y_pred + 1e-9) + (1 - y) * np.log(1 - y_pred + 1e-9))
      self.costs.append(cost)

      # Gradients
      dw = (1/n_samples) * np.dot(X.T, (y_pred - y))
      db = (1/n_samples) * np.sum(y_pred - y)

      # Update
      self.weights -= self.lr * dw
      self.bias -= self.lr * db

  def predict_proba(self, X):
    linear_model = np.dot(X, self.weights) + self.bias
    return self.sigmoid(linear_model)

  def predict(self, X):
    probs = self.predict_proba(X)
    return np.where(probs >= 0.5, 1, 0)

#------------------------------
#Train model
#------------------------------
model = LogisticRegressionScratch(lr=0.1, epochs=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

#------------------------------
#4. Confusion Matrix & Metrics
#------------------------------
TP = np.sum((y_test == 1) & (y_pred == 1))
TN = np.sum((y_test == 0) & (y_pred == 0))
FP = np.sum((y_test == 0) & (y_pred == 1))
FN = np.sum((y_test == 1) & (y_pred == 0))

accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP) if (TP + FP) > 0 else 0
recall = TP / (TP + FN) if (TP + FN) > 0 else 0
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print("Confusion Matrix:")
print("TP:", TP, "TN:", TN, "FP:", FP, "FN:", FN)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)

#------------------------------
#5a. Cost vs Iteration plot
#------------------------------
plt.figure()
plt.plot(model.costs)
plt.xlabel("Iterations")
plt.ylabel("Cost (Loss)")
plt.title("Training Loss vs Iterations")
plt.show()

#-------------------------------
#5b. ROC Curve (from scratch)
#-------------------------------
thresholds = np.linspace(0, 1, 100)
TPR = []
FPR = []

for t in thresholds:
  y_temp = np.where(y_prob >= t, 1, 0)

  TP_t = np.sum((y_test == 1) & (y_temp == 1))
  TN_t = np.sum((y_test == 0) & (y_temp == 0))
  FP_t = np.sum((y_test == 0) & (y_temp == 1))
  FN_t = np.sum((y_test == 1) & (y_temp == 0))

  tpr = TP_t / (TP_t + FN_t) if (TP_t + FN_t) > 0 else 0
  fpr = FP_t / (FP_t + TN_t) if (FP_t + TN_t) > 0 else 0

  TPR.append(tpr)
  FPR.append(fpr)

plt.figure()
plt.plot(FPR, TPR, label='ROC Curve')
plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve (Logistic Regression from Scratch)")
plt.legend()
plt.show()